name: Linting and Security

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Security audit for backend
        working-directory: BE/app
        run: npm audit --audit-level=high

      - name: Security audit for frontend
        working-directory: FE/app
        run: npm audit --audit-level=high
