name: Linting and Security

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: BE/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run dev &

      - name: Run performance test
        run: npx autocannon http://localhost:3000/api/v1/flight
  
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FE/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend lint
        run: npm run lint
  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'

  #     - name: Security audit for backend
  #       working-directory: BE/app
  #       run: npm audit --audit-level=high

  #     - name: Security audit for frontend
  #       working-directory: FE/app
  #       run: npm audit --audit-level=high
